name: Coupon as Service
values:
  - key: baseUrl
    value: 'http://localhost:3014'
    enabled: true
    type: default
  - key: password
    value: testpass
    enabled: true
    type: default
  - key: couponCode
    value: SAVE20
    enabled: true
    type: default
  - key: discountId
    value: ''
    enabled: true
    type: default
